### ISSUE TITLE
SRA Toolkit: Workaround to avoid crashing host due to BeeGFS overload

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/CBI-software#17]
# Issue

It turns out that `fasterq-dump` of the SRA Toolkit software can bring down a machine to the point where `w` and `ps` is unresponsive, although things such as `ls` works.  I've troubleshooted this a bit over at UCSF Wynton.

# Troubleshooting

Turns out that others have reported similar problems, e.g.

1. https://github.com/ncbi/sra-tools/issues/463, and
2. https://github.com/ncbi/sra-tools/issues/161

The 2nd is interesting because there's a comment https://github.com/ncbi/sra-tools/issues/161#issuecomment-808294889 pointing toward BeeGDS:

> We have seen issues before with fasterq-dump and beegfs; fasterq-dump does I/O from multiple threads, I suspect (I have no access to an installation of beegfs to verify) the file system driver doesn't like that and deadlocks. (A process can't respond to a signal when it is in kernel space, that why Ctrl+C doesn't work.)

which might also explain why `w` and `ps` doesn't work (or?)

Now, the above comment also mentions:

> ..., `fasterq-dump` uses a lot of temporary files, it is probably best to create these on a locally attached device. You can set the location with `-t|--temp` but the default is the cwd. ...

So, the fact that `fasterq-dump` uses `$PWD` for temp files could certainly explain why the BeeGFS gets hit too hard causing the above hang.  I think the reason why they're using `$PWD` is that they're worried about small, possibly RAM mounted `/tmp` folders been filled up with their big files.

BTW, I've posted some follow-up comments, which mostly are feature requests making it possible to change defaults via environment variables.

# Patch
I've updated [`module load CBI sratoolkit`](https://github.com/HenrikBengtsson/CBI-software/commit/9dd7150fc4c5c582ba49744e25333aaf58206486#diff-3282603ba9173b06586aab1a5631e01dbde1a4c4f6c66d7df4dc9241ee805a1c) to inject `--temp "$(mktemp -d)"` so that `fasterq-dump` will default to `$TMPDIR` instead of `$PWD`.  I do this by defining Bash function:

```sh
$ type fasterq-dump
fasterq-dump is a function
fasterq-dump () 
{ 
    command fasterq-dump --temp "$(mktemp -d)" "$@"
}
```

I've verified (on my local Ubuntu machine) that `fasterq-dump SRR000001` works and even `fasterq-dump --version` (despite that `--temp ...` option injected).

**Comment by HenrikBengtsson** [comment]
@hgputnam, I've just deployed these updates on C4, e.g.

```r
$ module load CBI sratoolkit

$ fasterq-dump --version

"fasterq-dump" version 2.11.0

$ type fasterq-dump
fasterq-dump is a function
fasterq-dump () 
{ 
    command fasterq-dump --temp "$(mktemp -d)" "$@"
}
```

**Comment by hgputnam** [comment]
Thanks. Do you think I should make listserv/slack announcements for stuff like this?

**Comment by HenrikBengtsson** [comment]
Nah. I've done some basic testing and it seems to work.  Let's cross the fingers that there aren't any corner cases where this causes problem.  If that happens, we'll hear about it.   Not having this patch in place is probably worse; Wynton dev nodes have gone done over the last year because of this bug.
