### ISSUE TITLE
Observation - Automated timeout seems to happen when long-running package installs are happening.

### ISSUE THREAD

**Issue by hgputnam** [HenrikBengtsson/CBI-software#73]
I was troubleshooting a C4 issue and testing installing Seurat from an Rstudio session via rsc. The browser screen went blank after a lot of time had past (don't know exactly how much). I was testing against a dev server which is pretty slow. Just wondering if the timeout detection code could be made to test for the case of long running package installs.

**Comment by HenrikBengtsson** [comment]
Moved to https://github.com/UCSF-CBI/rstudio-server-controller/issues/70
